{{- if not .Values.externalRedis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-externalredis
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ default "" .Values.externalRedis.password | quote }}
{{- end }}
