{{- if not .Values.externalDatabase.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-externaldb
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ default "" .Values.externalDatabase.password | quote }}
{{- end }}
