{{- if not .Values.moodle.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-moodle
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
type: Opaque
stringData:
  moodle-password: {{ default "" .Values.moodle.password | quote }}
{{- end }}