apiVersion: v2
name: moodle
description: >
  A Helm chart for deploying adorsys-gis/moodle-container with external
  database and Redis services.
type: application
version: 0.4.0
appVersion: "latest"
keywords:
  - moodle
  - lms
home: https://github.com/adorsys-gis/moodle-container
sources:
  - https://github.com/adorsys-gis/moodle-container
maintainers:
  - name: adorsys-gis
dependencies:
  - name: common
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts/
