name: Lint Codebase

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_DOCKERFILE_HADOLINT: "true"
          VALIDATE_GITHUB_ACTIONS: "true"
          VALIDATE_GITLEAKS: "true"
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: "true"
          VALIDATE_YAML: "true"
          VALIDATE_MARKDOWN: "true"
